services:
  web:
    image: yacine1108/brasilburger:latest
    environment:
      ConnectionStrings__DefaultConnection: "Host=ep-solitary-cake-a4najv73-pooler.us-east-1.aws.neon.tech;Port=5432;Database=brasil_burger_db;Username=neondb_owner;Password=npg_Vy0MDeICAi8h;Ssl Mode=Require;Channel Binding=Require"
      ASPNETCORE_URLS: "http://+:8080"
      PORT: "8080"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8083:8080"
    restart: unless-stopped
